llegadas/urls.py
from django.urls import path
from .views import (
ListLlegada,
DetailLlegada,
CreateLlegada,
UpdateLlegada,
DeleteLlegada,
SearchLlegada,
FilterLlegada,
export_llegada,
)

app_name = 'llegadas'

urlpatterns = [
    path('list/llegada/', ListLlegada.as_view(), name='list_llegada'),
    path('detail/llegada/<int:pk>/', DetailLlegada.as_view(), name='detail_llegada'),
    path('create/llegada/', CreateLlegada.as_view(), name='create_llegada'),
    path('update/llegada/<int:pk>/', UpdateLlegada.as_view(), name='update_llegada'),
    path('delete/llegada/<int:pk/', DeleteLlegada.as_view(), name='delete_llegada'),
    path('search/llegada/', SearchLlegada.as_view(), name='search_llegada'),
    path('filter/llegada/', FilterLlegada.as_view(), name='filter_llegada'),
    path('export/llegada/', export_llegada, name='export_llegada'),
]

niproyecciones/urls.py
from django.contrib import admin
admin.site.site_header = 'NI Hardware'
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('tareas/', include('tareas.urls', namespace='tareas')),
    path('consultas/', include('consultas.urls', namespace='consultas')),
    path('estaciones/', include('estaciones.urls', namespace='estaciones')),
    path('partes/', include('partes.urls', namespace='partes')),
    path('hw_proyecciones/', include('hw_proyecciones.urls', namespace='hw_proyecciones')),
    path('proyecciones/', include('proyecciones.urls', namespace='proyecciones')),
    path('hw_actividades/', include('hw_actividades.urls', namespace='hw_actividades')),
    path('consumos/', include('consumos.urls', namespace='consumos')),
    path('llegadas/', include('llegadas.urls', namespace='llegadas')),
    path('existencias/', include('existencias.urls', namespace='existencias')),
    path('resultados/', include('resultados.urls', namespace='resultados')),
    path('impactos/', include('impactos.urls', namespace='impactos')),
    path('formatos/', include('formatos.urls', namespace='formatos')),
    path('rastreos/', include('rastreos.urls', namespace='rastreos')),
    path('asignaciones/', include('asignaciones.urls', namespace='asignaciones')),
    path('adicionales/', include('adicionales.urls', namespace='adicionales')),

    # third
    path('advanced_filters/', include('advanced_filters.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (
HomeView,
Login,
Logout,
Signin,
)

app_name = 'users'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signin/', Signin.as_view(), name='signin'),
]

llegadas/models.py
from django.db import models

from django.urls import reverse
from partes import choices
from partes.models import Parte
from django.db.models.signals import post_save
from django.dispatch import receiver

class Llegada(models.Model):
    parte = models.OneToOneField(Parte, on_delete=models.CASCADE, blank=True, null=True)
    grupo_parte = models.CharField(max_length=255, choices=choices.GRUPO_PARTE_CHOICES, blank=True, null=True)
    w14 = models.PositiveIntegerField(default=0)
    w15 = models.PositiveIntegerField(default=0)
    w16 = models.PositiveIntegerField(default=0)
    w17 = models.PositiveIntegerField(default=0)
    w18 = models.PositiveIntegerField(default=0)
    w19 = models.PositiveIntegerField(default=0)
    w20 = models.PositiveIntegerField(default=0)
    w21 = models.PositiveIntegerField(default=0)
    w22 = models.PositiveIntegerField(default=0)
    w23 = models.PositiveIntegerField(default=0)
    w24 = models.PositiveIntegerField(default=0)
    w25 = models.PositiveIntegerField(default=0)
    w26 = models.PositiveIntegerField(default=0)
    w27 = models.PositiveIntegerField(default=0)
    w28 = models.PositiveIntegerField(default=0)
    w29 = models.PositiveIntegerField(default=0)
    w30 = models.PositiveIntegerField(default=0)
    w31 = models.PositiveIntegerField(default=0)
    w32 = models.PositiveIntegerField(default=0)
    w33 = models.PositiveIntegerField(default=0)
    w34 = models.PositiveIntegerField(default=0)
    w35 = models.PositiveIntegerField(default=0)
    w36 = models.PositiveIntegerField(default=0)
    w37 = models.PositiveIntegerField(default=0)
    w38 = models.PositiveIntegerField(default=0)
    w39 = models.PositiveIntegerField(default=0)
    w40 = models.PositiveIntegerField(default=0)
    w41 = models.PositiveIntegerField(default=0)
    w42 = models.PositiveIntegerField(default=0)
    w43 = models.PositiveIntegerField(default=0)
    w44 = models.PositiveIntegerField(default=0)
    w45 = models.PositiveIntegerField(default=0)
    w46 = models.PositiveIntegerField(default=0)
    w47 = models.PositiveIntegerField(default=0)
    w48 = models.PositiveIntegerField(default=0)
    w49 = models.PositiveIntegerField(default=0)
    w50 = models.PositiveIntegerField(default=0)
    w51 = models.PositiveIntegerField(default=0)
    w52 = models.PositiveIntegerField(default=0)

    estado = models.BooleanField(default=True, editable=False)
    subestado = models.BooleanField(default=False, editable=False)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('creado',)
        verbose_name = 'llegada'
        verbose_name_plural = 'llegadas'

    def __str__(self):
        return self.parte.parte_nokia

    def get_absolute_url(self):
        return reverse('llegadas:detail_llegada', kwargs={'pk': self.pk})

    @receiver(post_save, sender=Parte)
    def create_llegada(sender, instance, created, **kwargs):
        if created:
            llegada, new = Llegada.objects.get_or_create(parte=instance,
                                                         grupo_parte=instance.grupo_parte)

    @receiver(post_save, sender=Parte)
    def save_llegada(sender, instance, **kwargs):
        instance.llegada.grupo_parte = instance.grupo_parte
        instance.llegada.save()

llegadas/forms.py
from django import forms
from django.forms import ModelForm
from .models import Llegada

class LlegadaForm(ModelForm):
    class Meta:
        model = Llegada
        fields = '__all__'

class FilterLlegadaForm(ModelForm):
    class Meta:
        model = Llegada
        fields = ('parte', 'grupo_parte')

llegadas/views.py
from django.shortcuts import render
from django.views.generic import (
TemplateView,
ListView,
DetailView,
UpdateView,
CreateView,
DeleteView,
FormView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import LlegadaForm, FilterLlegadaForm
from .models import Llegada
import operator
from django.db.models import Q
from functools import reduce
from .resources import LlegadaResource
from django.http import HttpResponse
from django.utils import timezone
from django.conf import settings

TODAY = timezone.now()
WEEK = TODAY.isocalendar()[1]
WEEKDAY = TODAY.weekday()
if WEEKDAY == settings.VIERNES or WEEKDAY == settings.SABADO or WEEKDAY == settings.DOMINGO:
    WEEK = WEEK + 1

class ListLlegada(LoginRequiredMixin, ListView, FormView):
    login_url = 'users:home'
    model = Llegada
    template_name = 'llegada/list_llegada.html'
    paginate_by = 15
    form_class = FilterLlegadaForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(ListLlegada, self).get_context_data(**kwargs)
        weeks = list(range(14, 53))
        week = WEEK
        fields = [week for week in weeks if week >= WEEK]
        context['fields'] = fields
        context['week'] = week
        context['items'] = self.get_queryset
        context['all_items'] = str(Llegada.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context

class DetailLlegada(LoginRequiredMixin, DetailView):
    login_url = 'users:home'
    model = Llegada
    template_name = 'llegada/detail_llegada.html'

class CreateLlegada(LoginRequiredMixin, CreateView):
    login_url = 'users:home'
    form_class = LlegadaForm
    template_name = 'llegada/includes/partials/create_llegada.html'

class UpdateLlegada(LoginRequiredMixin, UpdateView):
    login_url = 'users:home'
    model = Llegada
    form_class = LlegadaForm
    template_name = 'llegada/includes/partials/update_llegada.html'

class DeleteLlegada(LoginRequiredMixin, DeleteView):
    login_url = 'users:home'
    model = Llegada
    template_name = 'llegada/includes/partials/delete_llegada.html'

class SearchLlegada(ListLlegada):

    def get_queryset(self):
        queryset = super(SearchLlegada, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                          (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(parte__parte_nokia__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(grupo_parte__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchLlegada, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context

class FilterLlegada(ListLlegada):
    query_dict = {}

    def get_queryset(self):
        queryset = super(FilterLlegada, self).get_queryset()
        request_dict = self.request.GET.dict()
        query_dict = { k: v for k, v in request_dict.items() if v if k != 'page' if k != 'paginate_by' }
        self.query_dict = query_dict
        queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(FilterLlegada, self).get_context_data(**kwargs)
        context['query_dict'] = self.query_dict
        context['result'] = self.get_queryset().count()
        return context

def export_llegada(request):
    llegada_resource = LlegadaResource()
    query_dict = request.GET.dict()
    queryset = Llegada.objects.filter(**query_dict)
    dataset = llegada_resource.export(queryset)
    response = HttpResponse(dataset.xlsx, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Llegada.xlsx"'
    return response

llegadas/templates/llegada/list_llegada.html
{% extends 'base.html' %}
{% load static %}
{% load filter_tags %}
{% block title %}Llegadas{% endblock title %}

{% block navbar %}
{% include 'dashboard/includes/partials/navbar.html' %}
{% endblock navbar %}

{% block sidebar %}
{% include 'dashboard/includes/partials/sidebar.html' %}
{% endblock sidebar %}

{% block content_dashboard %}

<main role="main" class="">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-2 border-bottom">
    <h2 class="text-dark">Llegadas</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button class="btn btn-sm btn-outline-secondary" onclick="return create_llegada('{% url 'llegadas:create_llegada' %}')">
          <span data-feather="plus"></span>
          Crear
        </button>
        <button class="btn btn-sm btn-outline-secondary disabled" id="update" onclick="return update_llegada(url_update)">
          <span data-feather="edit"></span>
          Actualizar
        </button>
        <button class="btn btn-sm btn-outline-secondary disabled" id="delete" onclick="return delete_llegada(url_delete)">
          <span data-feather="trash"></span>
          Borrar
        </button>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'llegadas:export_llegada' %}?{{query_dict|get_encoded_dict}}">
          <span data-feather="download"></span>
          Exportar
        </a>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle mr-2  disabled" id="action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="play"></span>
          Accion
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">link</a>
          <a class="dropdown-item" href="#">link</a>
        </div>
      </div>

      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="calendar"></span>
          Hoy
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">link</a>
          <a class="dropdown-item" href="#">link</a>
        </div>
      </div>

    </div>
  </div>
  <div class="d-flex justify-content-end flex-wrap flex-md-nowrap align-items-center">
    {% if result %}
    Se encontraron {{ result }} de  {{ all_items }} items
    {% else %}
    {% endif %}
    <a class="nav-link btn btn-light btn-sm ml-3" href="#" id="filter-toggle"><span data-feather="menu"></span> Filtrar</a>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-sm" id="table_llegada">
      <thead>
        {% include 'llegada/includes/partials/head_llegada.html' %}
      </thead>
      <tbody>
        {% for object in object_list %}
          {% include 'llegada/includes/partials/body_llegada.html' %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
<div class="row border-bottom d-flex justify-content-end align-items-center mr-2">
    {% include 'dashboard/includes/partials/nav_paginate.html' %}
</div>


<div class="modal fade" id="create_llegada" tabindex="-1" role="dialog" aria-hidden="true">

</div>

<div class="modal fade" id="update_llegada" tabindex="-1" role="dialog" aria-hidden="true">

</div>
{% endblock content_dashboard %}

{% block filter %}
{% include 'dashboard/includes/partials/filter.html' %}
{% endblock filter %}