niproyecciones/urls.py
from django.contrib import admin
admin.site.site_header = 'NI Hardware'
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('tareas/', include('tareas.urls', namespace='tareas')),
    path('consultas/', include('consultas.urls', namespace='consultas')),
    path('estaciones/', include('estaciones.urls', namespace='estaciones')),
    path('partes/', include('partes.urls', namespace='partes')),
    path('hw_proyecciones/', include('hw_proyecciones.urls', namespace='hw_proyecciones')),
    path('proyecciones/', include('proyecciones.urls', namespace='proyecciones')),
    path('hw_actividades/', include('hw_actividades.urls', namespace='hw_actividades')),
    path('consumos/', include('consumos.urls', namespace='consumos')),
    path('llegadas/', include('llegadas.urls', namespace='llegadas')),
    path('existencias/', include('existencias.urls', namespace='existencias')),
    path('resultados/', include('resultados.urls', namespace='resultados')),
    path('impactos/', include('impactos.urls', namespace='impactos')),
    path('formatos/', include('formatos.urls', namespace='formatos')),
    path('rastreos/', include('rastreos.urls', namespace='rastreos')),
    path('asignaciones/', include('asignaciones.urls', namespace='asignaciones')),
    path('adicionales/', include('adicionales.urls', namespace='adicionales')),

    # third
    path('advanced_filters/', include('advanced_filters.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

partes/urls.py
from django.urls import path
from .views import (
ListParte,
DetailParte,
CreateParte,
UpdateParte,
DeleteParte,
SearchParte,
FilterParte,
export_parte,

create_hw_parte,
update_hw_parte,
delete_hw_parte,
)

app_name = 'partes'

urlpatterns = [
    path('list/parte/', ListParte.as_view(), name='list_parte'),
    path('detail/parte/<int:pk>/', DetailParte.as_view(), name='detail_parte'),
    path('create/parte/', CreateParte.as_view(), name='create_parte'),
    path('update/parte/<int:pk>/', UpdateParte.as_view(), name='update_parte'),
    path('delete/parte/<int:pk/', DeleteParte.as_view(), name='delete_parte'),
    path('search/parte/', SearchParte.as_view(), name='search_parte'),
    path('filter/parte/', FilterParte.as_view(), name='filter_parte'),
    path('export/parte/', export_parte, name='export_parte'),

    path('create/hw/parte/', create_hw_parte, name='create_hw_parte'),
    path('update/hw/parte/', update_hw_parte, name='update_hw_parte'),
    path('delete/hw/parte/', delete_hw_parte, name='delete_hw_parte'),
]

users/urls.py
from django.urls import path
from .views import (
HomeView,
Login,
Logout,
Signin,
)

app_name = 'users'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signin/', Signin.as_view(), name='signin'),
]

partes/models.py
from django.db import models

from django.urls import reverse
from . import choices

class Parte(models.Model):
    cod_sap = models.CharField(max_length=255, blank=True, null=True)
    parte_nokia = models.CharField(max_length=255, blank=True, null=True, unique=True)
    capex = models.CharField(max_length=255, blank=True, null=True)
    grupo_parte = models.CharField(max_length=255, choices=choices.GRUPO_PARTE_CHOICES, blank=True, null=True)
    grupo_familia = models.CharField(max_length=255, choices=choices.GRUPO_FAMILIA_CHOICES, blank=True, null=True)
    grupo_numero = models.PositiveIntegerField(choices=choices.GRUPO_NUMERO_CHOICES, blank=True, null=True)
    impactar = models.CharField(max_length=255, choices=choices.IMPACTAR_CHOICES, default='Si')

    estado = models.BooleanField(default=True, editable=False)
    subestado = models.BooleanField(default=False, editable=False)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('creado',)
        verbose_name = 'parte'
        verbose_name_plural = 'partes'

    def __str__(self):
        return self.parte_nokia

    def get_absolute_url(self):
        return reverse('partes:detail_parte', kwargs={'pk': self.pk})

partes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Parte

class ParteForm(ModelForm):
    class Meta:
        model = Parte
        fields = '__all__'

class FilterParteForm(ModelForm):
    class Meta:
        model = Parte
        fields = '__all__'

partes/views.py
from django.shortcuts import render
from django.views.generic import (
TemplateView,
ListView,
DetailView,
UpdateView,
CreateView,
DeleteView,
FormView
)
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ParteForm, FilterParteForm
from .models import Parte
import operator
from django.db.models import Q
from functools import reduce
from .resources import ParteResource
from django.http import HttpResponse
from hw_proyecciones.models import HwParte

class ListParte(LoginRequiredMixin, ListView, FormView):
    login_url = 'users:home'
    model = Parte
    template_name = 'parte/list_parte.html'
    paginate_by = 15
    form_class = FilterParteForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(ListParte, self).get_context_data(**kwargs)
        context['items'] = self.get_queryset
        context['all_items'] = str(Parte.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context

class DetailParte(LoginRequiredMixin, DetailView):
    login_url = 'users:home'
    model = Parte
    template_name = 'parte/detail_parte.html'

class CreateParte(LoginRequiredMixin, CreateView):
    login_url = 'users:home'
    form_class = ParteForm
    template_name = 'parte/includes/partials/create_parte.html'

class UpdateParte(LoginRequiredMixin, UpdateView):
    login_url = 'users:home'
    model = Parte
    form_class = ParteForm
    template_name = 'parte/includes/partials/update_parte.html'

class DeleteParte(LoginRequiredMixin, DeleteView):
    login_url = 'users:home'
    model = Parte
    template_name = 'parte/includes/partials/delete_parte.html'

class SearchParte(ListParte):

    def get_queryset(self):
        queryset = super(SearchParte, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                          (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(cod_sap__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(parte_nokia__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(capex__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(grupo_parte__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(grupo_familia__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(grupo_numero__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchParte, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context

class FilterParte(ListParte):
    query_dict = {}

    def get_queryset(self):
        queryset = super(FilterParte, self).get_queryset()
        request_dict = self.request.GET.dict()
        query_dict = { k: v for k, v in request_dict.items() if v if k != 'page' if k != 'paginate_by' }
        self.query_dict = query_dict
        queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(FilterParte, self).get_context_data(**kwargs)
        context['query_dict'] = self.query_dict
        context['result'] = self.get_queryset().count()
        return context

def export_parte(request):
    parte_resource = ParteResource()
    query_dict = request.GET.dict()
    queryset = Parte.objects.filter(**query_dict)
    dataset = parte_resource.export(queryset)
    response = HttpResponse(dataset.xlsx, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Parte.xlsx"'
    return response

def create_hw_parte(request):
    hw_partes = HwParte.objects.all()
    partes = Parte.objects.all()
    for hw_parte in hw_partes:
        try:
            parte = partes.get(parte_nokia__iexact=hw_parte.nombre_nokia)
        except Parte.DoesNotExist:
            parte = Parte.objects.create(
                cod_sap=hw_parte.cod_capex,
                parte_nokia=hw_parte.nombre_nokia,
                capex=hw_parte.nombre_capex,
            )
    return HttpResponse(status=204)

def update_hw_parte(request):
    hw_partes = HwParte.objects.all()
    partes = Parte.objects.all()
    for hw_parte in hw_partes:
        try:
            parte = partes.get(parte_nokia__iexact=hw_parte.nombre_nokia)
            if parte.cod_sap != hw_parte.cod_capex or \
                parte.parte_nokia != hw_parte.nombre_nokia or \
                parte.capex != hw_parte.nombre_capex:

                parte.cod_sap = hw_parte.cod_capex
                parte.parte_nokia = hw_parte.nombre_nokia
                parte.capex = hw_parte.nombre_capex
                parte.save()

        except Parte.DoesNotExist:
            pass
    return HttpResponse(status=204)

def delete_hw_parte(request):
    hw_partes = HwParte.objects.all()
    partes = Parte.objects.all()
    for hw_parte in hw_partes:
        try:
            partes = partes.exclude(parte_nokia__iexact=hw_parte.nombre_nokia)
        except Estacion.DoesNotExist:
            pass
    partes.delete()
    return HttpResponse(status=204)

partes/templates/parte/list_parte.html
{% extends 'base.html' %}
{% load static %}
{% load filter_tags %}
{% block title %}Partes{% endblock title %}

{% block navbar %}
{% include 'dashboard/includes/partials/navbar.html' %}
{% endblock navbar %}

{% block sidebar %}
{% include 'dashboard/includes/partials/sidebar.html' %}
{% endblock sidebar %}

{% block content_dashboard %}

<main role="main" class="">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-2 border-bottom">
    <h2 class="text-dark">Partes</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button class="btn btn-sm btn-outline-secondary" onclick="return create_parte('{% url 'partes:create_parte' %}')">
          <span data-feather="plus"></span>
          Crear
        </button>
        <button class="btn btn-sm btn-outline-secondary disabled" id="update" onclick="return update_parte(url_update)">
          <span data-feather="edit"></span>
          Actualizar
        </button>
        <button class="btn btn-sm btn-outline-secondary disabled" id="delete" onclick="return delete_parte(url_delete)">
          <span data-feather="trash"></span>
          Borrar
        </button>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'partes:export_parte' %}?{{query_dict|get_encoded_dict}}">
          <span data-feather="download"></span>
          Exportar
        </a>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle mr-2  disabled" id="action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="play"></span>
          Accion
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">link</a>
          <a class="dropdown-item" href="#">link</a>
        </div>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="calendar"></span>
          Hoy
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">link</a>
          <a class="dropdown-item" href="#">link</a>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-end flex-wrap flex-md-nowrap align-items-center">
    {% if result %}
    Se encontraron {{ result }} de  {{ all_items }} items
    {% else %}
    {% endif %}
    <a class="nav-link btn btn-light btn-sm ml-3" href="#" id="filter-toggle"><span data-feather="menu"></span> Filtrar</a>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-sm" id="table_parte">
      <thead>
        {% include 'parte/includes/partials/head_parte.html' %}
      </thead>
      <tbody>
        {% for object in object_list %}
          {% include 'parte/includes/partials/body_parte.html' %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
<div class="row border-bottom d-flex justify-content-end align-items-center mr-2">
    {% include 'dashboard/includes/partials/nav_paginate.html' %}
</div>

<div class="modal fade" id="create_parte" tabindex="-1" role="dialog" aria-hidden="true">

</div>

<div class="modal fade" id="update_parte" tabindex="-1" role="dialog" aria-hidden="true">

</div>
{% endblock content_dashboard %}

{% block filter %}
{% include 'dashboard/includes/partials/filter.html' %}
{% endblock filter %}