asignaciones/urls.py
from django.urls import path
from .views import (
ListAsignacionBulk,
DetailAsignacionBulk,
CreateAsignacionBulk,
UpdateAsignacionBulk,
DeleteAsignacionBulk,
SearchAsignacionBulk,
FilterAsignacionBulk,
export_asignacion_bulk,

ListAsignacionAntena,
DetailAsignacionAntena,
CreateAsignacionAntena,
UpdateAsignacionAntena,
DeleteAsignacionAntena,
SearchAsignacionAntena,
FilterAsignacionAntena,
export_asignacion_antena,

ListEstadoPo,
DetailEstadoPo,
CreateEstadoPo,
UpdateEstadoPo,
DeleteEstadoPo,
SearchEstadoPo,
FilterEstadoPo,
export_estado_po,

ListPoZina,
DetailPoZina,
CreatePoZina,
UpdatePoZina,
DeletePoZina,
SearchPoZina,
FilterPoZina,
export_po_zina,

ListEstadoAntena,
DetailEstadoAntena,
CreateEstadoAntena,
UpdateEstadoAntena,
DeleteEstadoAntena,
SearchEstadoAntena,
FilterEstadoAntena,
export_estado_antena,

sitios_asignacion,
sitios_po,
asignacion_bolsa,
sobrantes,
asignacion_bulk,
)

app_name = 'asignaciones'

urlpatterns = [
    path('list/asignacion/bulk/', ListAsignacionBulk.as_view(), name='list_asignacion_bulk'),
    path('detail/asignacion/bulk/<int:pk>/', DetailAsignacionBulk.as_view(), name='detail_asignacion_bulk'),
    path('create/asignacion/bulk/', CreateAsignacionBulk.as_view(), name='create_asignacion_bulk'),
    path('update/asignacion/bulk/<int:pk>/', UpdateAsignacionBulk.as_view(), name='update_asignacion_bulk'),
    path('delete/asignacion/bulk/<int:pk>/', DeleteAsignacionBulk.as_view(), name='delete_asignacion_bulk'),
    path('search/asignacion/bulk/', SearchAsignacionBulk.as_view(), name='search_asignacion_bulk'),
    path('filter/asignacion/bulk/', FilterAsignacionBulk.as_view(), name='filter_asignacion_bulk'),
    path('export/asignacion/bulk/', export_asignacion_bulk, name='export_asignacion_bulk'),

    path('list/asignacion/antena/', ListAsignacionAntena.as_view(), name='list_asignacion_antena'),
    path('detail/asignacion/antena/<int:pk>/', DetailAsignacionAntena.as_view(), name='detail_asignacion_antena'),
    path('create/asignacion/antena/', CreateAsignacionAntena.as_view(), name='create_asignacion_antena'),
    path('update/asignacion/antena/<int:pk>/', UpdateAsignacionAntena.as_view(), name='update_asignacion_antena'),
    path('delete/asignacion/antena/<int:pk>/', DeleteAsignacionAntena.as_view(), name='delete_asignacion_antena'),
    path('search/asignacion/antena/', SearchAsignacionAntena.as_view(), name='search_asignacion_antena'),
    path('filter/asignacion/antena/', FilterAsignacionAntena.as_view(), name='filter_asignacion_antena'),
    path('export/asignacion/antena/', export_asignacion_antena, name='export_asignacion_antena'),

    path('list/estado/po/', ListEstadoPo.as_view(), name='list_estado_po'),
    path('detail/estado/po/<int:pk>/', DetailEstadoPo.as_view(), name='detail_estado_po'),
    path('create/estado/po/', CreateEstadoPo.as_view(), name='create_estado_po'),
    path('update/estado/po/<int:pk>/', UpdateEstadoPo.as_view(), name='update_estado_po'),
    path('delete/estado/po/<int:pk>/', DeleteEstadoPo.as_view(), name='delete_estado_po'),
    path('search/estado/po/', SearchEstadoPo.as_view(), name='search_estado_po'),
    path('filter/estado/po/', FilterEstadoPo.as_view(), name='filter_estado_po'),
    path('export/estado/po/', export_estado_po, name='export_estado_po'),

    path('list/po/zina/', ListPoZina.as_view(), name='list_po_zina'),
    path('detail/po/zina/<int:pk>/', DetailPoZina.as_view(), name='detail_po_zina'),
    path('create/po/zina/', CreatePoZina.as_view(), name='create_po_zina'),
    path('update/po/zina/<int:pk>/', UpdatePoZina.as_view(), name='update_po_zina'),
    path('delete/po/zina/<int:pk>/', DeletePoZina.as_view(), name='delete_po_zina'),
    path('search/po/zina/', SearchPoZina.as_view(), name='search_po_zina'),
    path('filter/po/zina/', FilterPoZina.as_view(), name='filter_po_zina'),
    path('export/po/zina/', export_po_zina, name='export_po_zina'),

    path('list/estado/antena/', ListEstadoAntena.as_view(), name='list_estado_antena'),
    path('detail/estado/antena/<int:pk>/', DetailEstadoAntena.as_view(), name='detail_estado_antena'),
    path('create/estado/antena/', CreateEstadoAntena.as_view(), name='create_estado_antena'),
    path('update/estado/antena/<int:pk>/', UpdateEstadoAntena.as_view(), name='update_estado_antena'),
    path('delete/estado/antena/<int:pk>/', DeleteEstadoAntena.as_view(), name='delete_estado_antena'),
    path('search/estado/antena/', SearchEstadoAntena.as_view(), name='search_estado_antena'),
    path('filter/estado/antena/', FilterEstadoAntena.as_view(), name='filter_estado_antena'),
    path('exestadort/estado/antena/', export_estado_antena, name='export_estado_antena'),

    path('sitios/asignacion/', sitios_asignacion, name='sitios_asignacion'),
    path('sitios/po/', sitios_po, name='sitios_po'),
    path('asignacion/bolsa/', asignacion_bolsa, name='asignacion_bolsa'),
    path('sobrantes/', sobrantes, name='sobrantes'),
    path('asignacion/bulk/', asignacion_bulk, name='asignacion_bulk'),
]

niproyecciones/urls.py
from django.contrib import admin
admin.site.site_header = 'NI Hardware'
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('tareas/', include('tareas.urls', namespace='tareas')),
    path('consultas/', include('consultas.urls', namespace='consultas')),
    path('estaciones/', include('estaciones.urls', namespace='estaciones')),
    path('partes/', include('partes.urls', namespace='partes')),
    path('hw_proyecciones/', include('hw_proyecciones.urls', namespace='hw_proyecciones')),
    path('proyecciones/', include('proyecciones.urls', namespace='proyecciones')),
    path('hw_actividades/', include('hw_actividades.urls', namespace='hw_actividades')),
    path('consumos/', include('consumos.urls', namespace='consumos')),
    path('llegadas/', include('llegadas.urls', namespace='llegadas')),
    path('existencias/', include('existencias.urls', namespace='existencias')),
    path('resultados/', include('resultados.urls', namespace='resultados')),
    path('impactos/', include('impactos.urls', namespace='impactos')),
    path('formatos/', include('formatos.urls', namespace='formatos')),
    path('rastreos/', include('rastreos.urls', namespace='rastreos')),
    path('asignaciones/', include('asignaciones.urls', namespace='asignaciones')),
    path('adicionales/', include('adicionales.urls', namespace='adicionales')),

    # third
    path('advanced_filters/', include('advanced_filters.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import (
HomeView,
Login,
Logout,
Signin,
)

app_name = 'users'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signin/', Signin.as_view(), name='signin'),
]

asignaciones/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    DeleteView,
    FormView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from .models import (
    AsignacionBulk,
    AsignacionAntena,
    EstadoPo,
    PoZina,
    EstadoAntena,
)
from .forms import (
    AsignacionBulkForm,
    FilterAsignacionBulkForm,
    AsignacionAntenaForm,
    FilterAsignacionAntenaForm,
    EstadoPoForm,
    FilterEstadoPoForm,
    PoZinaForm,
    FilterPoZinaForm,
    EstadoAntenaForm,
    FilterEstadoAntenaForm,
)
from .resources import (
    AsignacionBulkResource,
    AsignacionAntenaResource,
    EstadoPoResource,
    PoZinaResource,
    EstadoAntenaResource,
)
from .tasks import (
    task_sitios_asignacion,
    task_sitios_po,
    task_asignacion_bolsa,
    task_sobrantes,
    task_asignacion_bulk,
)
from tareas.models import Tarea
from estaciones.models import Estacion
from partes.models import Parte
import operator
from django.db.models import Q
from functools import reduce

class ListAsignacionBulk(LoginRequiredMixin,
                            ListView,
                            FormView):
    login_url = 'users:home'
    model = AsignacionBulk
    template_name = 'asignacion_bulk/list_asignacion_bulk.html'
    paginate_by = 15
    form_class = FilterAsignacionBulkForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(ListAsignacionBulk, self).get_context_data(**kwargs)
        context['items'] = self.get_queryset
        context['all_items'] = str(AsignacionBulk.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context

class DetailAsignacionBulk(LoginRequiredMixin, DetailView):
    login_url = 'users:home'
    model = AsignacionBulk
    template_name = 'asignacion_bulk/detail_asignacion_bulk.html'

class CreateAsignacionBulk(LoginRequiredMixin,
                            SuccessMessageMixin,
                            CreateView):
    login_url = 'users:home'
    success_message = "Asignacion Bulk fue creada exitosamente"
    form_class = AsignacionBulkForm
    template_name = 'asignacion_bulk/includes/partials/create_asignacion_bulk.html'

class UpdateAsignacionBulk(LoginRequiredMixin,
                            SuccessMessageMixin,
                            UpdateView):
    login_url = 'users:home'
    success_message = "Asignacion Bulk fue actualizada exitosamente"
    model = AsignacionBulk
    form_class = AsignacionBulkForm
    template_name = 'asignacion_bulk/includes/partials/update_asignacion_bulk.html'

class DeleteAsignacionBulk(LoginRequiredMixin,
                            DeleteView):
    login_url = 'users:home'
    model = AsignacionBulk
    template_name = 'asignacion_bulk/includes/partials/delete_asignacion_bulk.html'
    success_url = reverse_lazy('asignacion_bulks:list_asignacion_bulk')

class SearchAsignacionBulk(ListAsignacionBulk):

    def get_queryset(self):
        queryset = super(SearchAsignacionBulk, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                          (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(parte__parte_nokia__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(cod_sap__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(capex__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(cantidad__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(cod_bodega__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(bodega__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(comentario_bodega__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(so__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(po__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchAsignacionBulk, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context

class FilterAsignacionBulk(ListAsignacionBulk):
    query_dict = {}

    def get_queryset(self):
        queryset = super(FilterAsignacionBulk, self).get_queryset()
        request_dict = self.request.GET.dict()
        query_dict = { k: v for k, v in request_dict.items() if v if k != 'page' if k != 'paginate_by' }
        self.query_dict = query_dict
        queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(FilterAsignacionBulk, self).get_context_data(**kwargs)
        context['query_dict'] = self.query_dict
        context['result'] = self.get_queryset().count()
        return context

def export_asignacion_bulk(request):
    asignacion_bulk_resource = AsignacionBulkResource()
    query_dict = request.GET.dict()
    queryset = AsignacionBulk.objects.filter(**query_dict)
    dataset = asignacion_bulk_resource.export(queryset)
    response = HttpResponse(dataset.xlsx, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="AsignacionBulk.xlsx"'
    return response

class ListAsignacionAntena(LoginRequiredMixin,
                            ListView,
                            FormView):
    login_url = 'users:home'
    model = AsignacionAntena
    template_name = 'asignacion_antena/list_asignacion_antena.html'
    paginate_by = 15
    form_class = FilterAsignacionAntenaForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(ListAsignacionAntena, self).get_context_data(**kwargs)
        context['items'] = self.get_queryset
        context['all_items'] = str(AsignacionAntena.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context

class DetailAsignacionAntena(LoginRequiredMixin, DetailView):
    login_url = 'users:home'
    model = AsignacionAntena
    template_name = 'asignacion_antena/detail_asignacion_antena.html'

class CreateAsignacionAntena(LoginRequiredMixin,
                            SuccessMessageMixin,
                            CreateView):
    login_url = 'users:home'
    success_message = "Asignacion Antena fue creada exitosamente"
    form_class = AsignacionAntenaForm
    template_name = 'asignacion_antena/includes/partials/create_asignacion_antena.html'

class UpdateAsignacionAntena(LoginRequiredMixin,
                            SuccessMessageMixin,
                            UpdateView):
    login_url = 'users:home'
    success_message = "Asignacion Antena fue actualizada exitosamente"
    model = AsignacionAntena
    form_class = AsignacionAntenaForm
    template_name = 'asignacion_antena/includes/partials/update_asignacion_antena.html'

class DeleteAsignacionAntena(LoginRequiredMixin,
                            DeleteView):
    login_url = 'users:home'
    model = AsignacionAntena
    template_name = 'asignacion_antena/includes/partials/delete_asignacion_antena.html'
    success_url = reverse_lazy('asignacion_antenas:list_asignacion_antena')

class SearchAsignacionAntena(ListAsignacionAntena):

    def get_queryset(self):
        queryset = super(SearchAsignacionAntena, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                          (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(parte__parte_nokia__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(cod_sap__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(capex__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(cantidad__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(cod_bodega__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(bodega__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(familia__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(caracteristicas__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(puertos__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchAsignacionAntena, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context

class FilterAsignacionAntena(ListAsignacionAntena):
    query_dict = {}

    def get_queryset(self):
        queryset = super(FilterAsignacionAntena, self).get_queryset()

asignaciones/templates/estado_po/list_estado_po.html
{% extends 'base.html' %}
{% load static %}
{% load filter_tags %}
{% block title %}Estado Po{% endblock title %}
{% block extra_css %}
<link rel="stylesheet" href="{% static 'asignaciones/css/estado_po.css' %}"/>
{% endblock extra_css %}

{% block navbar %}
{% include 'dashboard/includes/partials/navbar.html' %}
{% endblock navbar %}

{% block sidebar %}
{% include 'dashboard/includes/partials/sidebar.html' %}
{% endblock sidebar %}

{% block content_dashboard %}

<main role="main" class="">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-2 border-bottom">
    <h2 class="text-dark">Estado Po</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button class="btn btn-sm btn-outline-secondary" onclick="return create_estado_po(url_create)">
          <span data-feather="plus"></span>
          Crear
        </button>
        <button class="btn btn-sm btn-outline-secondary disabled" id="update" onclick="return update_estado_po(url_update)">
          <span data-feather="edit"></span>
          Actualizar
        </button>
        <button class="btn btn-sm btn-outline-secondary disabled" id="delete" onclick="return delete_estado_po(url_delete)">
          <span data-feather="trash"></span>
          Borrar
        </button>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'asignaciones:export_estado_po' %}?{{query_dict|get_encoded_dict}}">
          <span data-feather="download"></span>
          Exportar
        </a>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle mr-2  disabled" id="action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="play"></span>
          Accion
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Detalle</a>
          <a class="dropdown-item" href="#">link</a>
        </div>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="calendar"></span>
          Hoy
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Creado</a>
          <a class="dropdown-item" href="#">Actualizado</a>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-end flex-wrap flex-md-nowrap align-items-center">
    {% if result %}
    Se encontraron {{ result }} de  {{ all_items }} items
    {% else %}
    {% endif %}
    <a class="nav-link btn btn-light btn-sm ml-3" href="#" id="filter-toggle"><span data-feather="menu"></span> Filtrar</a>
  </div>
  {% if messages %}
    {% for message in messages %}
    <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %} role="alert">
      <strong>OK!</strong> {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
  {% endif %}
  <div class="table-responsive">
    <table class="table table-striped table-sm" id="table_estado_po">
      <thead>
        {% include 'estado_po/includes/partials/head_estado_po.html' %}
      </thead>
      <tbody>
        {% for object in object_list %}
          {% include 'estado_po/includes/partials/body_estado_po.html' %}
        {% endfor %}
      </tbody>
    </table>
  </div> 
</main>
<div class="row border-bottom d-flex justify-content-end align-items-center mr-2">
  {% include 'dashboard/includes/partials/nav_paginate.html' %}
</div>
<div class="modal fade" id="create_estado_po" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div class="modal fade" id="update_estado_po" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div class="modal fade" id="delete_estado_po" tabindex="-1" role="dialog" aria-hidden="true"></div>
{% endblock content_dashboard %}

{% block filter %}
{% include 'dashboard/includes/partials/filter.html' %}
{% endblock filter %}

{% block extra_js %}
<script src="{% static 'asignaciones/js/estado_po.js' %}"></script>
{% endblock extra_js %}