niproyecciones/urls.py
from django.contrib import admin
admin.site.site_header = 'NI Hardware'
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('tareas/', include('tareas.urls', namespace='tareas')),
    path('consultas/', include('consultas.urls', namespace='consultas')),
    path('estaciones/', include('estaciones.urls', namespace='estaciones')),
    path('partes/', include('partes.urls', namespace='partes')),
    path('hw_proyecciones/', include('hw_proyecciones.urls', namespace='hw_proyecciones')),
    path('proyecciones/', include('proyecciones.urls', namespace='proyecciones')),
    path('hw_actividades/', include('hw_actividades.urls', namespace='hw_actividades')),
    path('consumos/', include('consumos.urls', namespace='consumos')),
    path('llegadas/', include('llegadas.urls', namespace='llegadas')),
    path('existencias/', include('existencias.urls', namespace='existencias')),
    path('resultados/', include('resultados.urls', namespace='resultados')),
    path('impactos/', include('impactos.urls', namespace='impactos')),
    path('formatos/', include('formatos.urls', namespace='formatos')),
    path('rastreos/', include('rastreos.urls', namespace='rastreos')),
    path('asignaciones/', include('asignaciones.urls', namespace='asignaciones')),
    path('adicionales/', include('adicionales.urls', namespace='adicionales')),

    # third
    path('advanced_filters/', include('advanced_filters.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

proyecciones/urls.py
from django.urls import path
from .views import (
ListProyeccion,
DetailProyeccion,
CreateProyeccion,
UpdateProyeccion,
DeleteProyeccion,
SearchProyeccion,
FilterProyeccion,
export_proyeccion,
send_proyeccion,
)

app_name = 'proyecciones'

urlpatterns = [
    path('list/proyeccion/web/', ListProyeccion.as_view(), name='list_proyeccion'),
    path('detail/proyeccion/web/<int:pk>/', DetailProyeccion.as_view(), name='detail_proyeccion'),
    path('create/proyeccion/web/', CreateProyeccion.as_view(), name='create_proyeccion'),
    path('update/proyeccion/web/<int:pk>/', UpdateProyeccion.as_view(), name='update_proyeccion'),
    path('delete/proyeccion/web/<int:pk/', DeleteProyeccion.as_view(), name='delete_proyeccion'),
    path('search/proyeccion/web/', SearchProyeccion.as_view(), name='search_proyeccion_web'),
    path('filter/proyeccion/web/', FilterProyeccion.as_view(), name='filter_proyeccion_web'),
    path('export/proyeccion/web/', export_proyeccion, name='export_proyeccion'),
    path('send/proyeccion/', send_proyeccion, name='send_proyeccion'),
]

users/urls.py
from django.urls import path
from .views import (
HomeView,
Login,
Logout,
Signin,
)

app_name = 'users'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signin/', Signin.as_view(), name='signin'),
]

proyecciones/models.py
from django.db import models

from django.urls import reverse
from . import choices
from estaciones.models import Estacion
from partes.models import Parte

class Proyeccion(models.Model):
    id = models.IntegerField(primary_key=True)
    estacion = models.ForeignKey(Estacion, on_delete=models.CASCADE, related_name='proyecciones', blank=True, null=True)
    proyecto = models.CharField(max_length=255, blank=True, null=True)
    escenario = models.CharField(max_length=255, blank=True, null=True)
    banda = models.CharField(max_length=255, blank=True, null=True)
    agrupadores = models.CharField(max_length=255, blank=True, null=True)
    rfe = models.DateField(blank=True, null=True)
    parte = models.ForeignKey(Parte, on_delete=models.CASCADE, related_name='proyecciones', blank=True, null=True)
    estado_proyeccion  = models.CharField(max_length=255, choices=choices.ESTADO_PROYECCION_CHOICES, blank=True, null=True)
    cantidad_estimada = models.PositiveIntegerField(blank=True, null=True)

    estado = models.BooleanField(default=True, editable=False)
    subestado = models.BooleanField(default=False, editable=False)
    creado = models.DateTimeField(auto_now_add=True)
    actualizado = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('creado',)
        verbose_name = 'proyeccion'
        verbose_name_plural = 'proyecciones'

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse('proyecciones:detail_proyeccion', kwargs={'pk': self.pk})

proyecciones/forms.py
from django import forms
from django.forms import ModelForm
from .models import Proyeccion

class ProyeccionForm(ModelForm):
    class Meta:
        model = Proyeccion
        fields = '__all__'

class FilterProyeccionForm(ModelForm):
    id = forms.IntegerField(required=False)
    
    class Meta:
        model = Proyeccion
        fields = '__all__'

proyecciones/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.generic import (
TemplateView,
ListView,
DetailView,
UpdateView,
CreateView,
DeleteView,
FormView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ProyeccionForm, FilterProyeccionForm
from .models import Proyeccion
import operator
from django.db.models import Q
from functools import reduce
from .resources import ProyeccionResource
from .tasks import send_mail_proyeccion
from tareas.models import Tarea

class ListProyeccion(LoginRequiredMixin, ListView, FormView):
    login_url = 'users:home'
    model = Proyeccion
    template_name = 'proyeccion/list_proyeccion.html'
    paginate_by = 15
    form_class = FilterProyeccionForm

    def get_paginate_by(self, queryset):
        return self.request.GET.get('paginate_by', self.paginate_by)

    def get_context_data(self, **kwargs):
        context = super(ListProyeccion, self).get_context_data(**kwargs)
        context['items'] = self.get_queryset
        context['all_items'] = str(Proyeccion.objects.all().count())
        context['paginate_by'] = self.request.GET.get('paginate_by', self.paginate_by)
        context['query'] = self.request.GET.get('qs')
        return context

class DetailProyeccion(LoginRequiredMixin, DetailView):
    login_url = 'users:home'
    model = Proyeccion
    template_name = 'proyeccion/detail_proyeccion.html'

class CreateProyeccion(LoginRequiredMixin, CreateView):
    login_url = 'users:home'
    form_class = ProyeccionForm
    template_name = 'proyeccion/includes/partials/create_proyeccion.html'

class UpdateProyeccion(LoginRequiredMixin, UpdateView):
    login_url = 'users:home'
    model = Proyeccion
    form_class = ProyeccionForm
    template_name = 'proyeccion/includes/partials/update_proyeccion.html'

class DeleteProyeccion(LoginRequiredMixin, DeleteView):
    login_url = 'users:home'
    model = Proyeccion
    template_name = 'proyeccion/includes/partials/delete_proyeccion.html'

class SearchProyeccion(ListProyeccion):

    def get_queryset(self):
        queryset = super(SearchProyeccion, self).get_queryset()
        query = self.request.GET.get('q')
        if query:
            query_list = query.split()
            queryset = queryset.filter(
                reduce(operator.and_,
                          (Q(id__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(estacion__site_name__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(proyecto__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(escenario__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(banda__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(agrupadores__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(parte__parte_nokia__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(estado_proyeccion__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                          (Q(cantidad_estimada__icontains=q) for q in query_list))
            )
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchProyeccion, self).get_context_data(**kwargs)
        context['result'] = self.get_queryset().count()
        return context

class FilterProyeccion(ListProyeccion):
    query_dict = {}

    def get_queryset(self):
        queryset = super(FilterProyeccion, self).get_queryset()
        dict = self.request.GET.dict()
        query_dict = { k: v for k, v in dict.items() if v if k != 'page' if k != 'paginate_by' }
        self.query_dict = query_dict
        queryset = queryset.filter(**query_dict)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(FilterProyeccion, self).get_context_data(**kwargs)
        context['query_dict'] = self.query_dict
        context['result'] = self.get_queryset().count()
        return context

def export_proyeccion(request):
    proyeccion_resource = ProyeccionResource()
    query_dict = request.GET.dict()
    queryset = Proyeccion.objects.filter(**query_dict)
    dataset = proyeccion_resource.export(queryset)
    response = HttpResponse(dataset.xlsx, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="Proyeccion.xlsx"'
    return response

def send_proyeccion(request):
    tarea_id = request.GET.get('tarea_id', None)
    tarea = Tarea.objects.get(id=tarea_id)
    task = send_mail_proyeccion.delay()
    tarea.tarea_id = task.id
    tarea.save()
    data = { 'task_id': task.id }
    return JsonResponse(data, safe=False)

proyecciones/templates/proyeccion/list_proyeccion.html
{% extends 'base.html' %}
{% load static %}
{% load filter_tags %}
{% block title %}Proyecciones{% endblock title %}

{% block navbar %}
{% include 'dashboard/includes/partials/navbar.html' %}
{% endblock navbar %}

{% block sidebar %}
{% include 'dashboard/includes/partials/sidebar.html' %}
{% endblock sidebar %}

{% block content_dashboard %}

<main role="main" class="">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center mt-2 border-bottom">
    <h2 class="text-dark">Proyecciones</h2>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button class="btn btn-sm btn-outline-secondary" onclick="return create_proyeccion('{% url 'proyecciones:create_proyeccion' %}')">
          <span data-feather="plus"></span>
          Crear
        </button>
        <button class="btn btn-sm btn-outline-secondary disabled" id="update" onclick="return update_proyeccion(url_update)">
          <span data-feather="edit"></span>
          Actualizar
        </button>
        <button class="btn btn-sm btn-outline-secondary disabled" id="delete" onclick="return delete_proyeccion(url_delete)">
          <span data-feather="trash"></span>
          Borrar
        </button>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'proyecciones:export_proyeccion' %}?{{query_dict|get_encoded_dict}}">
          <span data-feather="download"></span>
          Exportar
        </a>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle mr-2  disabled" id="action" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="play"></span>
          Accion
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">link</a>
          <a class="dropdown-item" href="#">link</a>
        </div>
      </div>
      <div class="btn-group" role="group">
        <button class="btn btn-sm btn-outline-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span data-feather="calendar"></span>
          Hoy
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">link</a>
          <a class="dropdown-item" href="#">link</a>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-end flex-wrap flex-md-nowrap align-items-center">
    {% if result %}
    Se encontraron {{ result }} de  {{ all_items }} items
    {% else %}
    {% endif %}
    <a class="nav-link btn btn-light btn-sm ml-3" href="#" id="filter-toggle"><span data-feather="menu"></span> Filtrar</a>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-sm" id="table_proyeccion">
      <thead>
        {% include 'proyeccion/includes/partials/head_proyeccion.html' %}
      </thead>
      <tbody>
        {% for object in object_list %}
          {% include 'proyeccion/includes/partials/body_proyeccion.html' %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</main>
<div class="row border-bottom d-flex justify-content-end align-items-center mr-2">
    {% include 'dashboard/includes/partials/nav_paginate.html' %}
</div>
<div class="modal fade" id="create_proyeccion" tabindex="-1" role="dialog" aria-hidden="true">
</div>
<div class="modal fade" id="update_proyeccion" tabindex="-1" role="dialog" aria-hidden="true">
</div>
{% endblock content_dashboard %}

{% block filter %}
{% include 'dashboard/includes/partials/filter.html' %}
{% endblock filter %}